### ISSUE TITLE
Vegetable,Fruit Bits etc...

### ISSUE THREAD

**Issue by sick13** [DefbeatCZ/DefsLTS#12]
Feature Request. Ability to cut various Vegetables,Fruit etc... with Bread knife, or simple knife,
not just Kitchen and Hunting Knife.

P.S
Keep it up this is an awesome mod!

**Comment by DefbeatCZ** [comment]
Make sense and should be implemented in 1.1
- Make sure to include most of blade-type tools/weapons per B41 changes

**Comment by DefbeatCZ** [comment]
- extended to all cooking recipes
- added BreadKnife, MeatCleaver, Machete, FlintKnife
