### ISSUE TITLE
Additional Recipes

### ISSUE THREAD

**Issue by sick13** [DefbeatCZ/DefsLTS#15]
Here are some additional recipes i think might be worth implementing feel free to remove/add/balance the way you think is best for your mod

```module Base
{
/************************Recipes************************/
	recipe Remove Screws
	{
	   Hinge=1,
	   keep Screwdriver,
	   
	   Result:Screws=1,
	   Sound:PZ_Hammer,
	   Time:25.0,
	   Category:Carpentry,
	}
	recipe Remove Screws
	{
	   Doorknob=1,
	   keep Screwdriver,

	   Result:Screws=1,
	   Sound:PZ_Hammer,
	   Time:25.0,
	   Category:Carpentry,
	}
	recipe Craft Mattress
	{
	   keep Needle=1,
	   Twine=5,
	   Pillow=5,
	   Sheet=5,

	   Result:Mattress=1,
	   Time:180.0,
	}
	recipe Craft Tissues
	{
	   Sheet=1,
	   keep Scissors/KitchenKnife/HuntingKnife=1,

	   Result:Tissue=2,
	   Sound:PZ_ClothesRipping,
	   Time:50.0,
	}
	recipe Rip Sheet Rope
	{
	   SheetRope=1,

	   Result:RippedSheets=2,
	   Sound:PZ_ClothesRipping,
	   Time:60.0,
	}
	recipe Rip Pillow
	{
		Pillow,
		Time 		: 350,
		Result 		: Sheet,
	}
	recipe Rip Dishcloth
	{
		destroy DishCloth,
		Sound 		: ClothesRipping,
		Time 		: 250,
		Result 		: RippedSheets=1,
	}
	recipe Rip Bath Towel
	{
		destroy BathTowel,
		Sound 		: ClothesRipping,
		Time 		: 350,
		Result 		: RippedSheets=1,
	}
}
```

**Comment by DefbeatCZ** [comment]
Very good tips for the tailoring (have few more in stock), but why would one need screws? I mean they are not used in Vanilla so for other mods I guess ...

**Comment by sick13** [comment]
yeah the screws are not for vanilla i thought you could integrate them in that ground storage unit, or something else that comes to mind...just an idea

**Comment by DefbeatCZ** [comment]
- The following is added 
Making Sheet by sewing Ripped Sheets together
Tearing Pillow cover to make Sheet
Tearing Sheet Rope to make Ripped Sheets
Tearing Dish Cloth/Towel to make Ripped Sheets
Making Tissues from either Ripped Sheets or Toilet Paper

- Screws will not be added at the moment as I have no (good) idea hot to make them useful.
- Mattress can be crafted by Vanilla recipe.
