### ISSUE TITLE
Unable to use drying rack

### ISSUE THREAD

**Issue by ArKanop** [DefbeatCZ/DefsLTS#31]
Not sure if it is a bug or is it just that i don't find the proper way to do it.
I tried to put the drying rack on the floor, on my inventory, on a box and equipping it, but i am unable to place bits of vegetable (or any other bit) inside.

Best regards

**Comment by DefbeatCZ** [comment]
The recipe needs 12 bits of vegs, empty rack and 2 units of salt. just verified as working by starting new game and spawning items in,

**Comment by ArKanop** [comment]
Ok, it works, thanks.
I was trying to use it by drag & drop, not by using the recipe. Maybe it is worth mentioning it on the Wiki? :)
